apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  - port: 5001
    protocol TCP
  selector:
    run: my-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-1
  labels:
    run: my-nginx-1
spec:
  ports:
  - port: 80
    protocol: TCP
  - port: 5001
    protocol TCP
  selector:
    run: my-nginx-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-1
spec:
  selector:
    matchLabels:
      run: my-nginx-1
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx-1
    spec:
      containers:
      - name: my-nginx-1
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 5001
---

